
employmentAgencyService:
  baseUrl: 'rest.arbeitsagentur.de'

  # job search
  jobSearchEndpoint: '/jobboerse/jobsuche-service/pc/v4/jobs'
  jobLogoEndpoint: 'jobboerse/jobsuche-service/ed/v1/arbeitgeberlogo'

  # oAuth
  oAuthEndpoint: '/oauth/gettoken_cc'

  clientId: 'c003a37f-024f-462a-b36d-b001be4cd24a'
  clientSecret: '32a39620-32b3-4307-9aa1-511e3d7f48a8'
  grantType: 'client_credentials'

sharedPreferences:
  eABearerToken: 'ea_bearer_token'
  eATokenValidUntil: 'ea_token_valid_until'
